### ISSUE TITLE
Failed migrations leave __LiquigraphLock in place

### ISSUE THREAD

**Issue by drago-dais** [liquigraph/liquigraph#220]
__LiquigraphLock is left in place whenever migration / changset fails.

Here's an excerpt from the log:
```
Cannot remove __LiquigraphLock during cleanup.

java.sql.SQLException: org.neo4j.driver.v1.exceptions.ClientException: Cannot run more statements in this transaction, because previous statements in the transaction has failed and the transaction has been rolled back. Please start a new transaction to run another statement.
        at org.neo4j.jdbc.bolt.BoltNeo4jPreparedStatement.executeInternal(BoltNeo4jPreparedStatement.java:105) ~[neo4j-jdbc-driver-3.3.1.jar!/:na]
        at org.neo4j.jdbc.bolt.BoltNeo4jPreparedStatement.execute(BoltNeo4jPreparedStatement.java:77) ~[neo4j-jdbc-driver-3.3.1.jar!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
        at org.neo4j.jdbc.utils.Neo4jInvocationHandler.invoke(Neo4jInvocationHandler.java:54) ~[neo4j-jdbc-driver-3.3.1.jar!/:na]
        at com.sun.proxy.$Proxy223.execute(Unknown Source) ~[na:na]
        at org.liquigraph.core.io.lock.LiquigraphLock.releaseLock(LiquigraphLock.java:123) [liquigraph-core-3.0.2.jar!/:na]
        at org.liquigraph.core.io.lock.LiquigraphLock.release(LiquigraphLock.java:54) [liquigraph-core-3.0.2.jar!/:na]
        at org.liquigraph.core.io.lock.LockableConnection.close(LockableConnection.java:103) [liquigraph-core-3.0.2.jar!/:na]
        at org.liquigraph.core.api.MigrationRunner.runMigrations(MigrationRunner.java:81) [liquigraph-core-3.0.2.jar!/:na]
        at org.liquigraph.core.api.Liquigraph.runMigrations(Liquigraph.java:63) [liquigraph-core-3.0.2.jar!/:na]
        at org.liquigraph.spring.SpringLiquigraph.afterPropertiesSet(SpringLiquigraph.java:52) [liquigraph-spring-boot-starter-3.0.2.jar!/:na]
        at 
```

To reproduce this, create changeset that fails (for example, create an invalid query).

This  was observed in a Spring Boot application, using org.liquigraph:liquigraph-spring-boot-starter:3.0.2.

**Comment by drago-dais** [comment]
To fix this, I had to do two things:
 * explicitly roll back current transaction before executing lock node cleanup statement, to cover the case where there is a failed, but not yet closed transaction
 * upgrade neo4j-jdbc-driver to 3.3.1 (because 3.1.0 does not start new transaction on rollback)

```
diff --git a/liquigraph-core/src/main/java/org/liquigraph/core/io/lock/LiquigraphLock.java b/liquigraph-core/src/main/java/org/liquigraph/core/io/lock/LiquigraphLock.java
index 5892856..25ea651 100644
--- a/liquigraph-core/src/main/java/org/liquigraph/core/io/lock/LiquigraphLock.java
+++ b/liquigraph-core/src/main/java/org/liquigraph/core/io/lock/LiquigraphLock.java
@@ -120,7 +120,11 @@ public class LiquigraphLock {
     private void releaseLock(Connection connection) {
         try (PreparedStatement statement = connection.prepareStatement(
                 "MATCH (lock:__LiquigraphLock {uuid:{1}}) DELETE lock")) {
-
+            if (!connection.getAutoCommit()){
+                // We need to ensure that lock removal runs as its own transaction, or otherwise
+                // we risk adding to an already failed transaction and leaving the lock in place.
+                connection.rollback();
+            }
             statement.setString(1, uuid.toString());
             statement.execute();
             connection.commit();
diff --git a/pom.xml b/pom.xml
index 1692ee3..686926f 100644
--- a/pom.xml
+++ b/pom.xml
@@ -31,7 +31,7 @@
         <generateBackupPoms>false</generateBackupPoms>
         <spring-boot.version>2.0.0.RELEASE</spring-boot.version>
         <jetty.version>9.2.9.v20150224</jetty.version>
-        <neo4j-jdbc.version>3.1.0</neo4j-jdbc.version>
+        <neo4j-jdbc.version>3.3.1</neo4j-jdbc.version>
     </properties>
 
     <modules>
```

**Comment by fbiville** [comment]
Hi, thanks a lot for your detailed analysis. I'll dig this a bit more, and port the fix to both 3.0 and 3.1 (and investigate if the same behavior is on 2.x).

**Comment by drago-dais** [comment]
Thanks a lot for such a quick reply!

An alternative to upgrading the jdbc driver to 3.3.x is to follow `connection.rollback()` with immediate `connection.commit()`. (This may be an interesting alternative for the older versions of liquigraph, where you may want to keep the jdbc driver at 3.1.0.)

To illustrate the jdbc driver issue, consider the following snippet:
```
        Properties props = new Properties();
        props.setProperty("user", "xxx");
        props.setProperty("password", "xxx");
        Connection conn = DriverManager.getConnection("jdbc:neo4j:bolt://localhost:7687", props);
        conn.setAutoCommit(false);
        Statement s = conn.createStatement();
        try {
            s.execute("one very invalid statement");
            System.out.println("results1:" + s.getResultSet());
        } catch (Exception e) {
            System.out.println("got: " + e);
            conn.rollback();
            //uncomment the following line for jdbc driver < 3.3.x
            //conn.commit();
            s = conn.createStatement();
            s.execute("return 2;");
            conn.commit();
            System.out.println("results2:" + s.getResultSet());
        }
        conn.close();
```

**Comment by fbiville** [comment]
Hey, apologies for getting back to this issue 1+ year later!
What I ended up doing (https://github.com/liquigraph/liquigraph/pull/246) is open a new connection if the cleanup fails, and re-attempt the cleanup with that new connection.
That way, the cleanup task can be performed regardless of the migration success status.

**Comment by fbiville** [comment]
Fixed in https://github.com/liquigraph/liquigraph/commit/09b8eb2514137f5b2e627b63068a625313774b8d. Feel free to re-open this issue if you encounter any problems.
