### ISSUE TITLE
"Failed to remove __LiquigraphLock. Trying again with new connection" error

### ISSUE THREAD

**Issue by paolodedo** [liquigraph/liquigraph#433]
Hello @fbiville ,

🟢Neo4j server: 4.2-aura Neo4j Enterprise Edt.
🟢SpringBoot: 2.4.1 (SDN 6.0.2)

🟢https://www.liquigraph.org/4.x/index.html : I am using Spring Boot approach.

🟢My changelog.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<changelog xmlns="http://www.liquigraph.org/schema/1.0/liquigraph.xsd">
    <changeset id="constraints-device" author="you">
        <query>CREATE CONSTRAINT unique_deviceId IF NOT EXISTS ON (device:Device) ASSERT device.deviceId IS UNIQUE</query>
        <query>CREATE CONSTRAINT notnull_deviceId IF NOT EXISTS ON (device:Device) ASSERT EXISTS (device.deviceId)</query>
    </changeset>
    <changeset id="constraints-group" author="you">
        <query>CREATE CONSTRAINT unique_groupId IF NOT EXISTS ON (group:Group) ASSERT group.groupId IS UNIQUE</query>
        <query>CREATE CONSTRAINT notnull_groupId IF NOT EXISTS ON (group:Group) ASSERT EXISTS (group.groupId)</query>
    </changeset>
</changelog>
```

🟢My pom.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.4.1</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    
....

    <properties>
        <java.version>11</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-neo4j</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-rest</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-hateoas</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>org.neo4j</groupId>
            <artifactId>neo4j-jdbc-http</artifactId>
            <version>4.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.liquigraph</groupId>
            <artifactId>liquigraph-spring-boot-starter</artifactId>
            <version>4.0.2</version>
        </dependency>
....
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>repackage</id>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                        <configuration>
                            <finalName>app</finalName>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
```

🟢My application.yml:

```
spring:
  neo4j:
    uri: ${DATASOURCE_CONNECTION_URL:neo4j+s://enterprise-neo4j:7687}
    authentication:
      username: ${DATASOURCE_USERNAME:neo4j}
      password: ${DATASOURCE_PASSWORD:psw}
  datasource:
    url: ${JDBC_DATASOURCE_CONNECTION_URL:jdbc:neo4j:http://enterprise-neo4j}
    driver-class-name: org.neo4j.jdbc.http.HttpDriver
    username: ${DATASOURCE_USERNAME:neo4j}
    password: ${DATASOURCE_PASSWORD:psw}
```

🔴🔴What happens is that Liquigraph returns:

```
2021-01-12 11:48:19.528  INFO 1404 --- [           main] o.l.core.io.lock.LiquigraphLock          : Failed to remove __LiquigraphLock. Trying again with new connection

java.sql.SQLException: java.sql.SQLException: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (org.apache.http.impl.io.EmptyInputStream); line: 1, column: 0]
	at org.neo4j.jdbc.http.driver.CypherExecutor.executeHttpRequest(CypherExecutor.java:421) ~[neo4j-jdbc-http-4.0.0.jar:na]
	at org.neo4j.jdbc.http.driver.CypherExecutor.executeQueries(CypherExecutor.java:223) ~[neo4j-jdbc-http-4.0.0.jar:na]
	at org.neo4j.jdbc.http.driver.CypherExecutor.executeQuery(CypherExecutor.java:236) ~[neo4j-jdbc-http-4.0.0.jar:na]
	at org.neo4j.jdbc.http.HttpNeo4jConnection.executeQuery(HttpNeo4jConnection.java:102) ~[neo4j-jdbc-http-4.0.0.jar:na]
	at org.neo4j.jdbc.http.HttpNeo4jPreparedStatement.execute(HttpNeo4jPreparedStatement.java:63) ~[neo4j-jdbc-http-4.0.0.jar:na]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[HikariCP-3.4.5.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[HikariCP-3.4.5.jar:na]
	at org.liquigraph.core.io.lock.LiquigraphLock.releaseLock(LiquigraphLock.java:151) ~[liquigraph-core-4.0.2.jar:na]
	at org.liquigraph.core.io.lock.LiquigraphLock.release(LiquigraphLock.java:64) ~[liquigraph-core-4.0.2.jar:na]
	at org.liquigraph.core.io.lock.LockableConnection.close(LockableConnection.java:102) ~[liquigraph-core-4.0.2.jar:na]
	at org.liquigraph.core.io.lock.LockableConnection.acquire(LockableConnection.java:77) ~[liquigraph-core-4.0.2.jar:na]
	at org.liquigraph.core.io.GraphJdbcConnector.connect(GraphJdbcConnector.java:44) ~[liquigraph-core-4.0.2.jar:na]
	at org.liquigraph.core.api.MigrationRunner$ConnectionSupplier.get(MigrationRunner.java:121) ~[liquigraph-core-4.0.2.jar:na]
	at org.liquigraph.core.api.MigrationRunner$ConnectionSupplier.get(MigrationRunner.java:111) ~[liquigraph-core-4.0.2.jar:na]
	at org.liquigraph.core.api.MigrationRunner.runMigrations(MigrationRunner.java:65) ~[liquigraph-core-4.0.2.jar:na]
	at org.liquigraph.core.api.Liquigraph.runMigrations(Liquigraph.java:101) ~[liquigraph-core-4.0.2.jar:na]
	at org.liquigraph.spring.SpringLiquigraph.afterPropertiesSet(SpringLiquigraph.java:60) ~[liquigraph-spring-boot-starter-4.0.2.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1847) ~[spring-beans-5.3.2.jar:5.3.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1784) ~[spring-beans-5.3.2.jar:5.3.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:609) ~[spring-beans-5.3.2.jar:5.3.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531) ~[spring-beans-5.3.2.jar:5.3.2]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.2.jar:5.3.2]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.2.jar:5.3.2]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.2.jar:5.3.2]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.2.jar:5.3.2]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.2.jar:5.3.2]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:923) ~[spring-context-5.3.2.jar:5.3.2]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588) ~[spring-context-5.3.2.jar:5.3.2]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.1.jar:2.4.1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) ~[spring-boot-2.4.1.jar:2.4.1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[spring-boot-2.4.1.jar:2.4.1]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) ~[spring-boot-2.4.1.jar:2.4.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) ~[spring-boot-2.4.1.jar:2.4.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309) ~[spring-boot-2.4.1.jar:2.4.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298) ~[spring-boot-2.4.1.jar:2.4.1]
```

Thanks.

**Comment by fbiville** [comment]
Thanks for reporting the issue!
Unfortunately, the stack trace does a bad job at showing what the problem.
The problem is actually quite simple: you can only connect to an Aura instance with Bolt, so you'll have to use the JDBC Bolt driver instead.

**Comment by paolodedo** [comment]
I have even tried with bolt..I think this is exactly what you are talking about.

-> `Caused by: java.lang.RuntimeException: Driver org.neo4j.jdbc.bolt.BoltDriver claims to not accept jdbcUrl, jdbc:bolt:http://localhost`


But why letting choose it, from application.yml?

![image](https://user-images.githubusercontent.com/25491113/104336133-6220c400-54f4-11eb-94a7-9a0614599e94.png)


Are there any other way to make these Cypher calls at the startup of my application? Even a Java class that launches script could be okay atm, since it'd give the functionality working..

Thank you

**Comment by fbiville** [comment]
I was about to update my previous comment :)

You have to configure the URL to be like `jdbc:neo4j:neo4j://HOST?encryption=true` and the driver class to be `org.neo4j.jdbc.boltrouting.BoltRoutingNeo4jDriver`.
I just tried it and it works.

**Comment by fbiville** [comment]
Let me know what kind of information is missing from the documentation so that I can complete it.

**Comment by fbiville** [comment]
For easier configuration in the future, I filed:
- https://github.com/neo4j-contrib/neo4j-jdbc/issues/248
- https://github.com/neo4j-contrib/neo4j-jdbc/issues/249

**Comment by paolodedo** [comment]
Thank you very much, it works this way (for local env, sufficient use ?encryption=false).

I think that, as Liquigraph docs is at the moment, is a little bit confusing and useless, since I have tried everything but didn't manage, on my own, to get it worked:

- starting from changelog.xml, Cypher syntax (ex: 'IS NOT NULL' doesn't work but is present on Neo4j Cypher's docs)
- datasource's url and driver-class-name (the ones you suggested me) are completely missing from the entire web
- I think that pom's dependency 

```
<dependency>
    <groupId>org.neo4j</groupId>
    <artifactId>neo4j-jdbc-bolt</artifactId>
    <!--<artifactId>neo4j-jdbc-http</artifactId>-->
    <version><!--see search.maven.org--></version>
</dependency>
```

should now be

```
<dependency>
	<groupId>org.neo4j</groupId>
	<artifactId>neo4j-jdbc-driver</artifactId>
	<version>4.0.1</version>
</dependency>
```


Anyway, thanks for the 2 issues you created, they'd simplify a lot in the future.

And, of course, thank you very much for your time and support.

🚀

**Comment by fbiville** [comment]
Hi, thanks for the feedback.
`neo4j-jdbc-driver` brings every Driver implementation (HTTP and Bolt) instead of a single one.
I will clarify the documentation to explain that.

I will also add the variant Driver class names and URLs.

Wrt to `IS NOT NULL`, this is another documentation altogether, i.e. the Cypher manual. Maybe the selected version can be made more visible?

**Comment by paolodedo** [comment]
Ok thank you very much :)

Yes, it is another doc, I know, but it could be useful to report these two examples (Unique and NotNull) on Liquigraph's doc as a lot of people in the web are trying to get them working.
