### ISSUE TITLE
Postgres and neo4j migration queries in the same Spring Boot project

### ISSUE THREAD

**Issue by suhasbhairav** [liquigraph/liquigraph#440]
How to handle both postgres and neo4j migration queries in the same project? I'm getting `"Could not ensure __LiquigraphLock uniqueness"` error when sql for postgres and changelog.xml for neo4j is present.

Neo4j version: 3.5.1

The stack trace is given below:
```
Caused by: org.liquigraph.core.exception.LiquigraphLockException: Could not ensure __LiquigraphLock uniqueness  Please make sure your instance is in a
clean state
        No more than 1 lock should be there simultaneously!
        at org.liquigraph.core.io.lock.LiquigraphLock.ensureLockUniqueness(LiquigraphLock.java:100) ~[liquigraph-core-3.1.2.jar:na]
        at org.liquigraph.core.io.lock.LiquigraphLock.acquire(LiquigraphLock.java:54) ~[liquigraph-core-3.1.2.jar:na]
        at org.liquigraph.core.io.lock.LockableConnection.acquire(LockableConnection.java:72) ~[liquigraph-core-3.1.2.jar:na]
        at org.liquigraph.core.io.GraphJdbcConnector.connect(GraphJdbcConnector.java:44) ~[liquigraph-core-3.1.2.jar:na]
        at org.liquigraph.core.api.MigrationRunner$ConnectionSupplier.get(MigrationRunner.java:121) ~[liquigraph-core-3.1.2.jar:na]
        at org.liquigraph.core.api.MigrationRunner$ConnectionSupplier.get(MigrationRunner.java:111) ~[liquigraph-core-3.1.2.jar:na]
        at org.liquigraph.core.api.MigrationRunner.runMigrations(MigrationRunner.java:65) ~[liquigraph-core-3.1.2.jar:na]
        at org.liquigraph.core.api.Liquigraph.runMigrations(Liquigraph.java:101) ~[liquigraph-core-3.1.2.jar:na]
        at org.liquigraph.spring.SpringLiquigraph.afterPropertiesSet(SpringLiquigraph.java:60) ~[liquigraph-spring-boot-starter-3.1.2.jar:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853)
 ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790) ~[
spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
        ... 17 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "ON"
  Position: 19
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553) ~[postgresql-42.2.16.jar:42.2.16]
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285) ~[postgresql-42.2.16.jar:42.2.16]
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323) ~[postgresql-42.2.16.jar:42.2.16]
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473) ~[postgresql-42.2.16.jar:42.2.16]
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393) ~[postgresql-42.2.16.jar:42.2.16]
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322) ~[postgresql-42.2.16.jar:42.2.16]
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308) ~[postgresql-42.2.16.jar:42.2.16]
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284) ~[postgresql-42.2.16.jar:42.2.16]
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:279) ~[postgresql-42.2.16.jar:42.2.16]
        at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95) ~[HikariCP-3.4.5.jar:na]
        at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-3.4.5.jar:na]
        at org.liquigraph.core.io.lock.LiquigraphLock.ensureLockUniqueness(LiquigraphLock.java:97) ~[liquigraph-core-3.1.2.jar:na]
        ... 27 common frames omitted
```

**Comment by fbiville** [comment]
Thanks for the report.
What version of Liquigraph are you using @suhasbhairav?

What seems to happen here is that Liquigraph is configured with the Postgres JDBC data source, not the Neo4j one, so syntax errors will happen.
How do you configure Liquigraph? Can you share the code/config files?

**Comment by suhasbhairav** [comment]
@fbiville Thank you for your reply. 

```yaml
spring:
  profiles:
    active: development
    jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
---
spring:
  profiles: development
  data:
    neo4j:
      uri: 'bolt://localhost:7687'
      #auto-index: validate
      use-native-types: true
  datasource:
    url: 'jdbc:postgresql://localhost/postgres'
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
```

The configuration above is the YAML file configuration for the project. Can you let me know if there is something missing from my side?

**Comment by fbiville** [comment]
Since Liquigraph is not explicitly configured, it will pick up the default configured data source (via `spring.datasource.*`), which is currently Postgres.

The easiest way about this is to configure Liquigraph specific properties, which have higher precedence over the (auto-configured) data source bean:

```yaml
liquigraph:
  url: jdbc:neo4j:${spring.data.neo4j.uri}
  user: ${spring.data.neo4j.username}
  password: ${spring.data.neo4j.password}
```

**Comment by fbiville** [comment]
Before I forget, Liquigraph will reach it end of life soon.
You should consider using https://neo4j.com/labs/liquibase/ instead.

**Comment by fbiville** [comment]
Did you solve your problem @suhasbhairav?

**Comment by fbiville** [comment]
Closing for now. Feel free to reopen @suhasbhairav if you consider this to still be an issue.

**Comment by suhasbhairav** [comment]
Sorry for the late reply. We are yet to solve it as we are still working on it. But I'll let you know if it's need to be reopened. @fbiville ..Thank you.
